#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// Project command
$application->add(new \Eliepse\Deployer\Command\CreateProjectCommand());
$application->add(new \Eliepse\Deployer\Command\InitProjectCommand());
$application->add(new \Eliepse\Deployer\Command\DeployProjectCommand());
$application->add(new \Eliepse\Deployer\Command\DestroyProjectCommand());

// Task command
$application->add(new \Eliepse\Deployer\Command\CreateTaskCommand());

$application->run();